language: php

php:
  - 7.2
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate -step

before_install:
- mysql -e 'CREATE DATABASE devLibrary_testing;'

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor